"use client";

import { Button } from "@/components/ui/button";
import { FileCheck } from "lucide-react";

interface ComplianceReportProps {
  result: {
    overall_ai_probability?: number;
    consensus_score?: number;
    consensus_verdict?: string;
    verdict?: string;
    reasoning?: string;
    patterns_summary?: string[];
    external_detectors?: {
      source: string;
      ai_probability: number;
      verdict: string;
      available: boolean;
    }[];
  };
  inputText: string;
  timestamp?: Date;
}

const verdictLabel: Record<string, string> = {
  likely_human: "Likely Human-Written",
  possibly_ai: "Possibly AI-Generated",
  likely_ai: "Likely AI-Generated",
  definitely_ai: "Definitely AI-Generated",
};

function getConfidenceLevel(score: number): string {
  if (score >= 0.85) return "Very High";
  if (score >= 0.65) return "High";
  if (score >= 0.4) return "Moderate";
  if (score >= 0.2) return "Low";
  return "Very Low";
}

export function ComplianceReport({ result, inputText, timestamp }: ComplianceReportProps) {
  function handlePrint() {
    window.print();
  }

  const analysisDate = timestamp || new Date();
  const reportId = `XCT-${analysisDate.getTime().toString(36).toUpperCase().slice(-8)}`;
  const wordCount = inputText.trim() ? inputText.trim().split(/\s+/).length : 0;
  const truncatedText = inputText.length > 500 ? inputText.slice(0, 500) + "..." : inputText;
  const overallPercent = result.overall_ai_probability
    ? Math.round(result.overall_ai_probability * 100)
    : 0;
  const consensusPercent = result.consensus_score !== undefined
    ? Math.round(result.consensus_score * 100)
    : null;

  return (
    <>
      {/* Print button - visible on screen */}
      <Button variant="outline" size="sm" onClick={handlePrint}>
        <FileCheck className="h-3.5 w-3.5" />
        Export Compliance Report
      </Button>

      {/* Print-only report */}
      <div className="hidden print:block print:!m-0 fixed inset-0 z-[9999] bg-white text-black p-8">
        {/* Header */}
        <div className="border-b-2 border-gray-800 pb-4 mb-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">AI Writing Compliance Report</h1>
              <p className="text-sm text-gray-500 mt-1">Generated by exCITE</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-gray-500">Report Date</p>
              <p className="text-sm font-medium">{analysisDate.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
              <p className="text-xs text-gray-500">{analysisDate.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })}</p>
              <p className="text-xs text-gray-500 mt-2">Report ID</p>
              <p className="text-sm font-mono">{reportId}</p>
            </div>
          </div>
        </div>

        {/* Overall Score */}
        <div className="mb-6 p-4 border-2 border-gray-300 rounded">
          <h2 className="text-lg font-bold mb-3">Overall Assessment</h2>
          <div className="grid grid-cols-3 gap-4">
            {consensusPercent !== null && (
              <div className="text-center">
                <p className="text-3xl font-bold">{consensusPercent}%</p>
                <p className="text-xs text-gray-500">Consensus AI Probability</p>
              </div>
            )}
            <div className="text-center">
              <p className="text-3xl font-bold">{overallPercent}%</p>
              <p className="text-xs text-gray-500">Claude AI Probability</p>
            </div>
            <div className="text-center">
              <p className="text-lg font-bold mt-1">
                {verdictLabel[result.verdict || ""] || result.verdict || "N/A"}
              </p>
              <p className="text-xs text-gray-500">Verdict</p>
            </div>
          </div>
          {consensusPercent !== null && (
            <div className="mt-2">
              <p className="text-xs text-gray-500">
                Confidence: {getConfidenceLevel(result.consensus_score ?? result.overall_ai_probability ?? 0)}
              </p>
            </div>
          )}
        </div>

        {/* Text Analyzed */}
        <div className="mb-6">
          <h2 className="text-lg font-bold mb-2">Text Analyzed</h2>
          <p className="text-xs text-gray-500 mb-1">{wordCount.toLocaleString()} words | {inputText.length.toLocaleString()} characters</p>
          <div className="p-3 bg-gray-50 border rounded text-sm leading-relaxed italic text-gray-700">
            &ldquo;{truncatedText}&rdquo;
          </div>
        </div>

        {/* Individual Detector Scores */}
        <div className="mb-6">
          <h2 className="text-lg font-bold mb-2">Detector Scores</h2>
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="border-b-2 border-gray-300">
                <th className="text-left py-2 pr-4">Source</th>
                <th className="text-left py-2 pr-4">AI Probability</th>
                <th className="text-left py-2">Verdict</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-gray-200">
                <td className="py-2 pr-4 font-medium">Claude Pattern Analysis</td>
                <td className="py-2 pr-4">{overallPercent}%</td>
                <td className="py-2">{verdictLabel[result.verdict || ""] || result.verdict || "N/A"}</td>
              </tr>
              {result.external_detectors?.map((detector, i) => (
                <tr key={i} className="border-b border-gray-200">
                  <td className="py-2 pr-4 font-medium">{detector.source}</td>
                  <td className="py-2 pr-4">
                    {detector.available ? `${Math.round(detector.ai_probability * 100)}%` : "Unavailable"}
                  </td>
                  <td className="py-2">
                    {detector.available ? (verdictLabel[detector.verdict] || detector.verdict) : "N/A"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Reasoning */}
        {result.reasoning && (
          <div className="mb-6">
            <h2 className="text-lg font-bold mb-2">Analysis Reasoning</h2>
            <p className="text-sm text-gray-700 leading-relaxed">{result.reasoning}</p>
          </div>
        )}

        {/* Detected Patterns */}
        {result.patterns_summary && result.patterns_summary.length > 0 && (
          <div className="mb-6">
            <h2 className="text-lg font-bold mb-2">Detected Patterns</h2>
            <ul className="list-disc list-inside text-sm text-gray-700 space-y-1">
              {result.patterns_summary.map((p, i) => (
                <li key={i}>{p}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Confidence Assessment */}
        <div className="mb-6">
          <h2 className="text-lg font-bold mb-2">Confidence Assessment</h2>
          <p className="text-sm text-gray-700">
            The analysis was performed using {1 + (result.external_detectors?.filter(d => d.available).length || 0)} detection source{(1 + (result.external_detectors?.filter(d => d.available).length || 0)) !== 1 ? "s" : ""}.
            {consensusPercent !== null
              ? ` The multi-source consensus score of ${consensusPercent}% reflects a weighted combination of Claude analysis (60%) and external detectors (40%).`
              : ` The score of ${overallPercent}% is based on Claude pattern analysis.`
            }
            {" "}Confidence level: {getConfidenceLevel(result.consensus_score ?? result.overall_ai_probability ?? 0)}.
          </p>
        </div>

        {/* Footer */}
        <div className="border-t-2 border-gray-800 pt-4 mt-8">
          <p className="text-sm font-medium text-gray-700">
            Generated by exCITE — Citation Intelligence for Healthcare &amp; Academia
          </p>
          <p className="text-xs text-gray-500 mt-1 italic">
            Report ID: {reportId} • This report is for informational purposes only and is not a legal document.
          </p>
          <div className="grid grid-cols-2 gap-8 mt-6">
            <div>
              <div className="border-t border-gray-400 pt-1">
                <p className="text-xs text-gray-500">Reviewer Signature</p>
              </div>
            </div>
            <div>
              <div className="border-t border-gray-400 pt-1">
                <p className="text-xs text-gray-500">Date</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
