export const metadata = { title: "Terms of Use — exCITE" };

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <h1 className="text-2xl font-bold tracking-tight">Terms of Use</h1>

      <div className="prose prose-sm dark:prose-invert max-w-none space-y-6">
        <p className="text-muted-foreground">
          Last updated: April 17, 2026
        </p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using exCITE (Citation Intelligence Tool for
            Healthcare &amp; Academia), you agree to be bound by these Terms of
            Use. If you do not agree, you may not use the service.
          </p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>
            exCITE is an AI-powered medical writing assistant that helps
            healthcare professionals and researchers analyze clinical notes,
            draft and rewrite manuscripts, generate and format citations, detect
            AI-generated text, and perform medical coding lookups. The service
            is powered by Claude, developed by Anthropic, and is hosted on
            Vercel. exCITE is currently available free of charge during its beta
            period.
          </p>
        </section>

        <section>
          <h2>3. User Responsibilities</h2>
          <ul>
            <li>
              You are solely responsible for reviewing, validating, and
              verifying all output generated by the service, including
              citations, medical codes, rewritten text, and analysis results.
            </li>
            <li>
              Although exCITE includes HIPAA-compliant automatic redaction of
              Protected Health Information (PHI), you should avoid inputting
              sensitive patient data unless necessary. You are responsible for
              ensuring your use complies with all applicable privacy laws and
              institutional policies.
            </li>
            <li>
              You agree not to use the service for any unlawful purpose or in
              any way that could damage, disable, or impair the service.
            </li>
          </ul>
        </section>

        <section>
          <h2>4. Medical Disclaimer</h2>
          <p>
            exCITE is <strong>not a medical device</strong> and does{" "}
            <strong>not provide medical advice</strong>, diagnosis, or
            treatment recommendations. The service is not a substitute for
            professional medical judgment. All clinical decisions must be made
            by qualified healthcare professionals exercising independent
            judgment. Nothing produced by exCITE should be relied upon as a
            basis for patient care without independent verification.
          </p>
        </section>

        <section>
          <h2>5. AI-Generated Content Disclaimer</h2>
          <p>
            All output produced by exCITE — including citations, coding
            suggestions, manuscript rewrites, and text analysis — is generated
            by artificial intelligence and may contain errors, omissions, or
            inaccuracies. AI-generated citations may reference works that do
            not exist or contain incorrect bibliographic details.{" "}
            <strong>
              You must independently verify all AI-generated content before
              use in any professional, academic, or clinical context.
            </strong>
          </p>
        </section>

        <section>
          <h2>6. Intellectual Property</h2>
          <p>
            You retain ownership of all text and content you submit to exCITE,
            as well as the output generated from your inputs. The exCITE name,
            logo, and underlying software are the intellectual property of
            their respective owners. You may not copy, modify, or redistribute
            the application itself without prior written permission.
          </p>
        </section>

        <section>
          <h2>7. Privacy &amp; Data Handling</h2>
          <p>
            exCITE automatically scans all submitted text for Protected Health
            Information and redacts detected PHI (including names, dates of
            birth, medical record numbers, Social Security numbers, and
            addresses) before processing. Despite these safeguards, no
            automated system is perfect. You should minimize the inclusion of
            PHI in your inputs whenever possible. Your use of the service is
            also governed by our Privacy Policy.
          </p>
        </section>

        <section>
          <h2>8. Limitation of Liability</h2>
          <p>
            The service is provided &ldquo;as is&rdquo; and &ldquo;as
            available&rdquo; without warranties of any kind, express or
            implied. To the fullest extent permitted by law, exCITE and its
            operators shall not be liable for any indirect, incidental,
            special, consequential, or punitive damages, or any loss of data,
            revenue, or profits arising from your use of or inability to use
            the service. This includes, without limitation, any errors in
            AI-generated output or any failure of PHI redaction.
          </p>
        </section>

        <section>
          <h2>9. Modifications to Terms</h2>
          <p>
            We reserve the right to modify these Terms of Use at any time.
            Changes will be posted on this page with an updated revision date.
            Your continued use of the service after any changes constitutes
            acceptance of the revised terms.
          </p>
        </section>

        <section>
          <h2>10. Termination</h2>
          <p>
            We may suspend or terminate your access to exCITE at any time, with
            or without cause, and without prior notice. Upon termination, your
            right to use the service ceases immediately.
          </p>
        </section>

        <section>
          <h2>11. Governing Law</h2>
          <p>
            These terms shall be governed by and construed in accordance with
            the laws of the United States. Any disputes arising under these
            terms shall be subject to the exclusive jurisdiction of the
            applicable federal or state courts.
          </p>
        </section>

        <section>
          <h2>12. Contact</h2>
          <p>
            If you have questions about these Terms of Use, please contact us
            at{" "}
            <a href="mailto:support@excite.health" className="underline">
              support@excite.health
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
